image: golang:1.10
stages:
    - build
  
before_script:
    - go get gitlab.com/bestmethod/go-acp
    - cp -r /builds/bestmethod /go/src/github.com/bestmethod/
    - cd /go/src/gitlab.com/bestmethod/go-acp

build:
    stage: build
  script:
    - godep restore
    - godep go build
